name = "blog-chen-gio"
main = "@astrojs/cloudflare/entrypoints/server"
compatibility_date = "2025-01-15"

[assets]
directory = "./dist"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "blog-comments"
database_id = "fe151766-b61b-4eb6-ae46-9a63bdb1676f"
